name: Changelog Test

# 手动触发
on:
  workflow_dispatch:

jobs:
  changelog-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Release
        id: release
        uses: MatteoCampinoti94/changelog-to-release@v1.0.0
        with:
          version-name: 'Unreleased'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: v0.6.8.1
          name: ${{ steps.release.outputs.title }}
          body: ${{ steps.release.outputs.body }}
